### PR TITLE
Fix snake_case and remove `failOnError`

### LINKED ISSUE #25: snake_case fails semistandard checks
As of semistandard v8 [snake_case is an error](https://github.com/Flet/semistandard/issues/111):

```
> lambda-taggable-createdocument@2.0.2 lint /Users/hassy/workspaces/tc/lambda-taggable-createDocument
> semistandard  --verbose | snazzy

semistandard: Semicolons For All! (https://github.com/Flet/semistandard)

/Users/hassy/workspaces/tc/lambda-taggable-createDocument/test/handler.test.js
  3:5  error  Identifier 'test_hotel_tag' is not in camel case  camelcase
  4:5  error  Identifier 'fields_list' is not in camel case     camelcase

/Users/hassy/workspaces/tc/lambda-taggable-createDocument/test/index.test.js
  5:5  error  Identifier 'test_hotel_tag' is not in camel case  camelcase

/Users/hassy/workspaces/tc/lambda-taggable-createDocument/test/s3_create.test.js
   4:5   error  Identifier 's3_create' is not in camel case  camelcase
   5:5   error  Identifier 'base_url' is not in camel case   camelcase
  28:32  error  Identifier 'base_url' is not in camel case   camelcase
  46:32  error  Identifier 'base_url' is not in camel case   camelcase
```

We should convert the rest of the codebase to camelCase gradually as well.

### PR DESCRIPTION
**Pull request by hassy**
- Fixes #25
- Updates for https://github.com/numo-labs/aws-lambda-helper/commit/3ec8ce082188cae9ea1ee23cb394f27d983e4ea6

### CODE REVIEW

**Comment by hassy** [comment]
Two `if (err) {}` branches are set to be ignored for coverage - I don't see an easy way to test those branches, maybe @nelsonic can offer some ideas? (Personally I'd be happy ignoring those for coverage).

**Comment by tomgco** [comment]
> Two if (err) {} branches are set to be ignored for coverage - I don't see an easy way to test those branches, maybe @nelsonic can offer some ideas? (Personally I'd be happy ignoring those for coverage).

Should be easy to use `sinon` and mock / stub those handler.methods to always return an error and assert that the failed callback is called?

**Comment by hassy** [comment]
@tomgco Yeah, I'll do that.

Those two branches would only be exercised if:

- Invoking the `lambda-taggable-geonames` lambda fails
- Uploading to the S3 bucket fails

So a test that exercises those branches is literally testing the implementation, but I guess you must do that for 100% coverage (not sold on this personally).

**Comment by nelsonic** [comment]
@hassy *no objection* to the `/* istanbul ignore if */` the `handler.initTagDoc` should not throw an error ... and jumping through hoops using mocks in order to throw and error is "*testing the implementation*" ...

**Comment by hassy** [comment]
Added tests to cover those anyway :)

**Comment by nelsonic** [comment]
@hassy cool. 🍭

**Pull request merged**
